---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml

vars:
  PROJECT_NAME:
    sh: echo ${PWD##*/}
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD); else echo main ; fi
  DAGGER_GO_MODULE: ~/projects/blueprints/go-microservice/ #github.com/stuttgart-things/blueprints/go-microservice  #@{{ .DAGGER_GO_MODULE_VERSION }}
  DAGGER_GO_MODULE_VERSION: v1.11.0
  GO_MODULE: github.com/stuttgart-things/k2n

dotenv: ['.env', '{{.HOME}}/.env']

tasks:
  ci-static:
    desc: Run static checks
    vars:
      STATIC_REPORT_PATH: /tmp/{{ .PROJECT_NAME }}/{{ .PROJECT_NAME }}-static.json
    cmds:
      - |
        dagger call -m {{ .DAGGER_GO_MODULE }} \
        run-static-stage \
        --src ./ \
        --goVersion 1.24.1 \
        --lintCanFail=true \
        --lintTimeout 500s \
        -vv --progress plain \
        export --path={{ .STATIC_REPORT_PATH }}
        code {{ .STATIC_REPORT_PATH }}

  ci-build:
    desc: Build binary + image
    vars:
      BUILD_PATH: /tmp/{{ .PROJECT_NAME }}
    cmds:
      - |
        dagger call -m {{ .DAGGER_GO_MODULE }} \
        run-build-stage \
        --src ./ \
        --ko-build=false \
        --bin-name {{ .PROJECT_NAME }} \
        --ldflags "cmd.version=$(git describe --tags --abbrev=0); cmd.commit=$(git rev-parse --short HEAD); cmd.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        --packageName {{ .GO_MODULE }} \
        -vv --progress plain \
        export --path={{ .BUILD_PATH }}
        ls -lta {{ .BUILD_PATH }}
        {{ .BUILD_PATH }}/{{ .PROJECT_NAME }} version

  run-only-prompt:
    desc: run the application with prompt but without sending data to AI
    cmds:
      - |
        go run main.go gen \
        --examples-dirs _examples/examples \
        --ruleset-env-dir _examples/ruleset-env \
        --ruleset-usecase-dir _examples/ruleset-runner \
        --usecase crosssplane \
        --verbose=true \
        --prompt-to-ai=false \
        --instruction "give me a runner-claim for the repository dagger for the cluster sthings"

  run-and-test:
    desc: run and test the application
      - |
        go run main.go gen \
        --examples-dirs _examples/examples \
        --ruleset-env-dir _examples/ruleset-env \
        --ruleset-usecase-dir _examples/ruleset-runner \
        --usecase crosssplane \
        --instruction "give me a runner-claim for the repository dagger for the cluster sthings"

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | \
          sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
# check: https://github.com/act3-ai/dagger/blob/main/release/main.go
